[package]
name = "akaze"
version = "0.2.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2018"
description = "AKAZE feature extraction algorithm for computer vision"
keywords = ["keypoint", "descriptor", "vision", "sfm", "slam"]
categories = ["computer-vision", "science::robotics"]
repository = "https://github.com/rust-cv/akaze"
documentation = "https://docs.rs/akaze/"
license = "MIT"
readme = "README.md"

[dependencies]
image = { version = "0.23.2", default-features = false }
log = { version = "0.4.8", default-features = false }
primal = { version = "0.2.3", default-features = false }
cv-core = { version = "0.9.1", default-features = false }
derive_more = { version = "0.99.5", default-features = false }
ndarray-image = { version = "0.2.1", default-features = false }
ndarray = { version = "0.13.0", default-features = false }
float-ord = { version = "0.2.0", default-features = false }
space = { version = "0.10.3", features = ["simd-hamming"] }


[dev-dependencies]
eight-point = "0.3.0"
arrsac = "0.3.0"
cv-core = { version = "0.9.1", features = ["pinhole"] }
space = { version = "0.10.3", features = ["simd"] }
rand = "0.7.3"
rand_pcg = "0.2.1"
criterion = "0.3.1"
pretty_env_logger = "0.4.0"
image = "0.23.2"

[[bench]]
name = "criterion"
harness = false

[profile.dev]
# The tests take a very long time without optimization.
opt-level = 3

[profile.bench]
# Necessary to generate flamegraphs
debug = true
codegen-units = 1
