[package]
name = "ensure_no_std"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2021"

[dependencies]
akaze = { path = ".." }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
