[package]
name = "chapter2-first-program"
version = "0.1.0"
authors = ["codec-abc <viot.camille@outlook.com>"]
edition = "2018"

[dependencies]
cv = { version = "0.6.0", path = "../../cv" }
image = "0.23.7"
imageproc = "0.21.0"
rand = "0.7.3"